export interface FAQItem {
  question: string;
  answer: string;
}

export interface ToolData {
  slug: string;
  title: string;
  description: string;
  features: string[];
  useCases: string[];
  faq: FAQItem[];
  content: string; // Markdown content
}

export const toolsData: ToolData[] = [
  {
    slug: "email-generator",
    title: "Email Subject Line Generator",
    description: "Generate catchy, high-converting email subject lines instantly.",
    features: [
      "AI-Powered Creativity: Uses advanced NLP to generate unique hooks.",
      "Tone Selection: Choose between Professional, Urgent, Funny, or Curious tones.",
      "Instant Results: Get 5+ variations in seconds.",
      "Mobile Optimized: Works perfectly on any device.",
      "Copy & Paste: One-click copy functionality."
    ],
    useCases: [
      "Newsletter Marketing: Increase your open rates with better hooks.",
      "Cold Outreach: Get your sales emails read by busy prospects.",
      "Internal Communication: Write clear subject lines for team updates.",
      "Event Invitations: Create excitement for your webinars or launch parties."
    ],
    faq: [
      {
        question: "Is this tool free?",
        answer: "Yes, the Email Subject Line Generator is 100% free to use. You don't need to sign up or provide a credit card."
      },
      {
        question: "How does it work?",
        answer: "We use OpenAI's GPT models to analyze your topic and generate subject lines based on proven marketing formulas (like FOMO, Curiosity gaps, etc.)."
      },
      {
        question: "Can I use these subject lines for commercial emails?",
        answer: "Absolutely! You own all the content generated by this tool."
      },
      {
        question: "How can I improve my open rates?",
        answer: "Keep your subject lines under 50 characters, use emojis sparingly, and try to evoke curiosity or urgency."
      }
    ],
    content: `
## Why Your Subject Line Matters

The subject line is the gatekeeper of your email. According to studies, **47% of email recipients open an email based on the subject line alone**. If your subject line fails, your perfectly crafted email body will never be read.

### The Science of a Good Subject Line

Writing a good subject line is part art, part science. Here are the key elements that our AI analyzes:

1.  **Urgency:** Does it compel the user to act now? (e.g., "Last chance to save 50%")
2.  **Curiosity:** Does it open a "curiosity gap" that can only be closed by opening the email? (e.g., "You won't believe what we just built...")
3.  **Relevance:** Is it personal and relevant to the recipient?
4.  **Brevity:** Mobile devices truncate long subject lines. We aim for concise impact.

### How to Use This Tool Effectively

*   **Be Specific:** Instead of just "Marketing", try "Marketing tips for small business owners".
*   **Test Tones:** Generate a "Funny" version and a "Professional" version and see which one fits your brand better.
*   **A/B Test:** If you have an email list, take two generated options and run an A/B test to see which one performs better.

### Common Mistakes to Avoid

*   **Clickbait:** Don't promise something in the subject line that isn't in the email. This hurts your deliverability and trust.
*   **ALL CAPS:** Using all caps can trigger spam filters and looks like shouting.
*   **Too Many Emojis:** Use one or two emojis to stand out, but don't overdo it.

Start generating better subject lines today and watch your open rates climb!
    `
  },
  // Placeholder for other tools to ensure the page works for them too
  // In a real scenario, we would fill these out individually.
  ...[
    "paraphraser", "social-post", "meta-description", "grammar-check", 
    "product-description", "blog-ideas", "youtube-ideas", "hashtag-generator", 
    "business-name", "code-explainer", "text-summarizer", "instagram-caption"
  ].map(slug => ({
    slug,
    title: slug.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' '),
    description: "AI-powered tool to boost your productivity.",
    features: [
      "Fast and reliable AI generation.",
      "Simple, user-friendly interface.",
      "No login required.",
      "Secure processing."
    ],
    useCases: [
      "Content Creation",
      "Productivity Enhancement",
      "Learning & Education"
    ],
    faq: [
      {
        question: "Is this tool free?",
        answer: "Yes, this tool is completely free to use."
      },
      {
        question: "How accurate is the AI?",
        answer: "We use state-of-the-art models (GPT-4o/Mini) to ensure high-quality results."
      }
    ],
    content: `
## About This Tool

This tool leverages advanced Artificial Intelligence to help you automate tasks and improve quality. 

### Benefits
*   **Save Time:** Automate repetitive tasks in seconds.
*   **Improve Quality:** Get professional-grade output without the effort.
*   **Boost Creativity:** Overcome writer's block and get new ideas.

### How it Works
Simply enter your input in the box above, select your preferences, and click "Generate". Our AI processes your request and delivers the results instantly.
    `
  }))
];

export function getToolData(slug: string): ToolData | undefined {
  return toolsData.find(t => t.slug === slug);
}

