export interface FAQItem {
  question: string;
  answer: string;
}

export interface ToolData {
  slug: string;
  title: string;
  description: string;
  features: string[];
  useCases: string[];
  faq: FAQItem[];
  content: string; // Markdown content
}

export const toolsData: ToolData[] = [
  {
    slug: "email-generator",
    title: "Email Subject Line Generator",
    description: "Generate catchy, high-converting email subject lines instantly.",
    features: [
      "AI-Powered Creativity: Uses advanced NLP to generate unique hooks.",
      "Tone Selection: Choose between Professional, Urgent, Funny, or Curious tones.",
      "Instant Results: Get 5+ variations in seconds.",
      "Mobile Optimized: Works perfectly on any device.",
      "Copy & Paste: One-click copy functionality."
    ],
    useCases: [
      "Newsletter Marketing: Increase your open rates with better hooks.",
      "Cold Outreach: Get your sales emails read by busy prospects.",
      "Internal Communication: Write clear subject lines for team updates.",
      "Event Invitations: Create excitement for your webinars or launch parties."
    ],
    faq: [
      {
        question: "Is this tool free?",
        answer: "Yes, the Email Subject Line Generator is 100% free to use. You don't need to sign up or provide a credit card."
      },
      {
        question: "How does it work?",
        answer: "We use OpenAI's GPT models to analyze your topic and generate subject lines based on proven marketing formulas (like FOMO, Curiosity gaps, etc.)."
      },
      {
        question: "Can I use these subject lines for commercial emails?",
        answer: "Absolutely! You own all the content generated by this tool."
      },
      {
        question: "How can I improve my open rates?",
        answer: "Keep your subject lines under 50 characters, use emojis sparingly, and try to evoke curiosity or urgency."
      }
    ],
    content: `
## Why Your Subject Line Matters

The subject line is the gatekeeper of your email. According to studies, **47% of email recipients open an email based on the subject line alone**. If your subject line fails, your perfectly crafted email body will never be read.

### The Science of a Good Subject Line

Writing a good subject line is part art, part science. Here are the key elements that our AI analyzes:

1.  **Urgency:** Does it compel the user to act now? (e.g., "Last chance to save 50%")
2.  **Curiosity:** Does it open a "curiosity gap" that can only be closed by opening the email? (e.g., "You won't believe what we just built...")
3.  **Relevance:** Is it personal and relevant to the recipient?
4.  **Brevity:** Mobile devices truncate long subject lines. We aim for concise impact.

### How to Use This Tool Effectively

*   **Be Specific:** Instead of just "Marketing", try "Marketing tips for small business owners".
*   **Test Tones:** Generate a "Funny" version and a "Professional" version and see which one fits your brand better.
*   **A/B Test:** If you have an email list, take two generated options and run an A/B test to see which one performs better.

### Common Mistakes to Avoid

*   **Clickbait:** Don't promise something in the subject line that isn't in the email. This hurts your deliverability and trust.
*   **ALL CAPS:** Using all caps can trigger spam filters and looks like shouting.
*   **Too Many Emojis:** Use one or two emojis to stand out, but don't overdo it.

Start generating better subject lines today and watch your open rates climb!
    `
  },
  // Placeholder for other tools to ensure the page works for them too
  // In a real scenario, we would fill these out individually.
  ...[
    "paraphraser", "social-post", "meta-description", "grammar-check", 
    "product-description", "blog-ideas", "youtube-ideas", "hashtag-generator", 
    "business-name", "code-explainer", "text-summarizer", "instagram-caption"
  ].map(slug => ({
    slug,
    title: slug.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' '),
    description: "AI-powered tool to boost your productivity.",
    features: [
      "Fast and reliable AI generation.",
      "Simple, user-friendly interface.",
      "No login required.",
      "Secure processing."
    ],
    useCases: [
      "Content Creation",
      "Productivity Enhancement",
      "Learning & Education"
    ],
    faq: [
      {
        question: "Is this tool free?",
        answer: "Yes, UtilityGenAI offers this tool completely free of charge for unlimited use."
      },
      {
        question: "Does it change the meaning of my text?",
        answer: "No, the core algorithm is designed to preserve the original message while changing the vocabulary and structure."
      }
    ],
    content: `
## What is an AI Paraphrasing Tool?
An AI paraphrasing tool is a sophisticated software designed to rewrite text while retaining its original meaning. Unlike simple synonym swappers, our tool understands context, tone, and nuance, making it perfect for students, writers, and professionals who need to refresh their content without losing clarity.

## How to Use This Tool Effectively
Getting the best results is simple. Follow these steps:
1. **Paste your text:** Copy the content you want to rewrite into the input box above.
2. **Select a Mode:** Choose between 'Standard', 'Fluency', or 'Creative' modes depending on your needs.
3. **Click Generate:** Let the AI analyze and rewrite your sentences in seconds.
4. **Review and Edit:** Always review the output to ensure it perfectly matches your intended tone.

## Why Choose UtilityGenAI?
While there are many rewriters available, our tool focuses on readability and SEO-friendliness. It removes plagiarism risks by creating unique sentence structures. Whether you are writing an academic essay, a blog post, or a business email, this tool helps you communicate more effectively.

## Frequently Asked Questions (FAQ)
**Is this tool free?**
Yes, UtilityGenAI offers this tool completely free of charge for unlimited use.

**Does it change the meaning of my text?**
No, the core algorithm is designed to preserve the original message while changing the vocabulary and structure.`
  }))
];

export function getToolData(slug: string): ToolData | undefined {
  return toolsData.find(t => t.slug === slug);
}

